// Generated by https://quicktype.io

export interface IAvailableFilters {
  id: string;
  name: string;
  type: string;
  values: Value[];
}

export interface Value {
  id: string;
  name: string;
  results: number;
}
