// Generated by https://quicktype.io

export interface IAvailableFilters {
  id: string;
  name: string;
  type: string;
  values: IFiltersValue[];
}

export interface IFiltersValue {
  id: string;
  name: string;
  results: number;
}
